### ISSUE TITLE
views/*.vue 组件包含的子组件若存在style标签，该路由渲染报错document is no defined

### ISSUE THREAD

**Issue by mjbin** [lentoo/vue-cli-ssr-example#1]

**Comment by mjbin** [comment]
你好，
       我的路由修改为不存在’/‘路径的情况下
![image](https://user-images.githubusercontent.com/3965629/47005956-6c15ba00-d167-11e8-97bf-1e644de8aa50.png)

**Comment by qiaer** [comment]
上同

**Comment by qiaer** [comment]
> 你好，
> 我的路由修改为不存在’/‘路径的情况下
> ![image](https://user-images.githubusercontent.com/3965629/47005956-6c15ba00-d167-11e8-97bf-1e644de8aa50.png)
> 在这种情况下就会报标题所示的错误
> 貌似不管路由是什么，根据测试，在about.vue 组件中引入一个子组件（包含style标签），那么/about 这个路由就会在服务端渲染的时候报错

![image](https://user-images.githubusercontent.com/24616514/47625760-162b1400-db62-11e8-9118-94c1cfa49258.png)

**Comment by lentoo** [comment]
我的并不会报错，你可以下载最新代码再试试

**Comment by VanquisherMe** [comment]
@lentoo 如果你在 import 注入的组件中加入一个 子组件，测试环境是可以的，生产环境会报 document is no defined 正在尝试解决，你有好的方案么

**Comment by lentoo** [comment]
在vue.config.js 添加
css:{
extract:false
}

**Comment by zc-eason** [comment]
> 在vue.config.js 添加
> css:{
> extract:false
> }

@lentoo   你好, 加了css这个后document不报错了, 又报了一个replace的错误, 不知道你们有没有遇到;
将`vue-server-renderer`build.prod.js换成build.dev.js, 报下面错
`TypeError: Cannot read property 'replace' of undefined
      at normalizeFile (/Users/demons/libs/mall_webapp/node_modules/vue-server-renderer/build.dev.js:9083:27)
      at Array.map (<anonymous>)
      at TemplateRenderer.getUsedAsyncFiles (/Users/demons/libs/mall_webapp/node_modules/vue-server-renderer/build.dev.js:9069:54)
      at TemplateRenderer.getPreloadFiles (/Users/demons/libs/mall_webapp/node_modules/vue-server-renderer/build.dev.js:8963:29)
      at TemplateRenderer.renderPreloadLinks (/Users/demons/libs/mall_webapp/node_modules/vue-server-renderer/build.dev.js:8974:20)
      at TemplateRenderer.renderResourceHints (/Users/demons/libs/mall_webapp/node_modules/vue-server-renderer/build.dev.js:8959:15)
      at TemplateRenderer.render (/Users/demons/libs/mall_webapp/node_modules/vue-server-renderer/build.dev.js:8915:12)
      at RenderContext.done (/Users/demons/libs/mall_webapp/node_modules/vue-server-renderer/build.dev.js:9177:42)
      at RenderContext.next (/Users/demons/libs/mall_webapp/node_modules/vue-server-renderer/build.dev.js:2588:19)
      at RenderContext.cachedWrite [as write] (/Users/demons/libs/mall_webapp/node_modules/vue-server-renderer/build.dev.js:2451:9)`

**Comment by lentoo** [comment]
@zc-eason 版本不一致产生的问题，重新拉取下我的demo试试
