### ISSUE TITLE
Error: Server-side bundle should have one single entry file.

### ISSUE THREAD

**Issue by bluelovers** [lentoo/vue-cli-ssr-example#15]
```
|  Building for production...(node:6480) UnhandledPromiseRejectionWarning: Error: Server-side bundle should have one single entry file. Avoid using CommonsChunkPlugin in the server config.
    at G:\Users\The Project\nodejs-vue\vue-cli-ssr-example\node_modules\vue-server-renderer\server-plugin.js:68:13
    at _next1 (eval at create (G:\Users\The Project\nodejs-vue\vue-cli-ssr-example\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (G:\Users\The Project\nodejs-vue\vue-cli-ssr-example\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:22:1)
    at callback (G:\Users\The Project\nodejs-vue\vue-cli-ssr-example\node_modules\copy-webpack-plugin\dist\index.js:77:17)
    at G:\Users\The Project\nodejs-vue\vue-cli-ssr-example\node_modules\copy-webpack-plugin\dist\index.js:118:24
(node:6480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which
was not handled with .catch(). (rejection id: 1)
(node:6480) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit c
ode.
|  Building for production...
```

**Comment by lentoo** [comment]
package.json 修改一下 build:server 改成这个试试 "build:server": "cross-env WEBPACK_TARGET=node vue-cli-service build --mode server",
